---
title: 'Meetnet habitatkwaliteit: verkennende analyses'
author: "Toon Westra"
date: "juli 2017"
output:
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
    subtitle: "Tussentijds technisch rapport"
    reportnr: "Intern Rapport"
    citation_package: none
    keep_tex: yes
  bookdown::gitbook: default
site: bookdown::bookdown_site
header-includes: 
  - \usepackage{placeins}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
---


```{r results ='hide', echo = FALSE, message = FALSE, purl = FALSE, warning=FALSE}

library(knitr)
opts_chunk$set(
  echo = FALSE, 
  results = 'markup',
  eval = TRUE,
  cache = TRUE,
  autodep = TRUE,
  dev = "pdf",
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  warning = FALSE,
  error = TRUE,
  message = FALSE
)

library(pander) # best eerst knitr en daarna pas pander laden


#theme_set(theme_bw(base_size = 9))

```


```{r Rinit,  warning = FALSE, message = FALSE, results = 'hide', cache = FALSE}

source("../scripts/Omgevingsvariabelen_versie2016-10-12.R")
source("../scripts/LSVI/LSVI_functies.R") 

library(tidyr)
library(dplyr)
library(tibble)
library(stringr)
library(ggmap)
library(kableExtra)
```
```{r Plotfunctie,  warning = FALSE, message = FALSE, results = 'hide', cache = FALSE}
plot_indicatoren <- function(DataIndicatoren, HabCode ){
  
p1 <- ggplot(DataIndicatoren[DataIndicatoren$HabCode == HabCode & DataIndicatoren$Criterium == "vegetatie",], aes(x = Waarde, y =  RangNr, colour = BeoordelingTekst)) + geom_point() + facet_grid(Criterium ~ AnalyseVariabele, scales = "free_x", labeller = labeller(AnalyseVariabele = label_wrap_gen(10)))+ labs(colour = "Beoordeling", y = "Meetpunt") + scale_colour_manual(values = colors_beoordeling) + theme(legend.position = "Hide", strip.text = element_text(size=8))

p2 <-ggplot(DataIndicatoren[DataIndicatoren$HabCode == HabCode & DataIndicatoren$Criterium == "habitatstructuur",], aes(x = Waarde, y =  RangNr, colour = BeoordelingTekst)) + geom_point() + facet_grid(Criterium ~ AnalyseVariabele, scales = "free_x" , labeller = labeller(AnalyseVariabele = label_wrap_gen(10)))+ labs(colour = "Beoordeling", y = "Meetpunt") + scale_colour_manual(values = colors_beoordeling) + theme(legend.position = "Hide",  strip.text = element_text(size=8))

p3 <- ggplot(DataIndicatoren[DataIndicatoren$HabCode == HabCode & DataIndicatoren$Criterium == "verstoring",], aes(x = Waarde, y =  RangNr, colour = BeoordelingTekst)) + geom_point() + facet_grid(Criterium ~ AnalyseVariabele, scales = "free_x" , labeller = labeller(AnalyseVariabele = label_wrap_gen(10)))+ labs(colour = "Beoordeling", y = "Meetpunt") + scale_colour_manual(values = colors_beoordeling) + theme(legend.position = "bottom",  strip.text = element_text(size=8))

grid.arrange(p1,p2,p3)

}




plot_beoordeling <- function(DataIndicatoren, HabCode ){
  
p1 <- ggplot(indicatoren[indicatoren$HabCode == HabCode & indicatoren$Criterium == "vegetatie",], aes(x = BeoordelingTekst, fill = BeoordelingTekst)) + geom_bar() + facet_grid(Criterium ~ Indicator + AnalyseVariabele ) + labs(x = "Beoordeling" ,fill = "Beoordeling", title = paste("Beoordeling indicatoren habitattype ",HabCode))

p2 <-ggplot(indicatoren[indicatoren$HabCode == HabCode & indicatoren$Criterium == "habitatstructuur",], aes(x = BeoordelingTekst, fill = BeoordelingTekst)) + geom_bar() + facet_grid(Criterium ~ AnalyseVariabele ) + labs(x = "Beoordeling" ,fill = "Beoordeling")

p3 <- ggplot(indicatoren[indicatoren$HabCode == HabCode & indicatoren$Criterium == "verstoring",], aes(x = BeoordelingTekst, fill = BeoordelingTekst)) + geom_bar() + facet_grid(Criterium ~ AnalyseVariabele ) + labs(x = "Beoordeling" ,fill = "Beoordeling")

grid.arrange(p1,p2,p3)

  
}

plot_beoordeling2 <- function(DataIndicatoren, HabCode ){
  
p1 <- ggplot(indicatoren[indicatoren$HabCode == HabCode & indicatoren$Criterium == "vegetatie",], aes(x = AnalyseVariabele, fill = BeoordelingTekst)) + geom_bar() + facet_wrap(~ Criterium ) + labs(x = "Analysevariabele" ,fill = "Beoordeling", title = paste("Beoordeling indicatoren habitattype ",HabCode), y = "Aantal meetpunten") + coord_flip()
#+ theme(axis.text.x = element_text(angle = 90, hjust = 1))

p2 <-ggplot(indicatoren[indicatoren$HabCode == HabCode & indicatoren$Criterium == "habitatstructuur",], aes(x = AnalyseVariabele, fill = BeoordelingTekst)) + geom_bar() + facet_wrap(~ Criterium ) + labs(x = "AnalyseVariabele" ,fill = "Beoordeling", y = "Aantal meetpunten") + coord_flip()
#+ theme(axis.text.x = element_text(angle = 90, hjust = 1))

p3 <- ggplot(indicatoren[indicatoren$HabCode == HabCode & indicatoren$Criterium == "verstoring",], aes(x = AnalyseVariabele, fill = BeoordelingTekst)) + geom_bar() + facet_wrap(~ Criterium ) + labs(x = "AnalyseVariabele" ,fill = "Beoordeling", y = "Aantal meetpunten") + coord_flip()
#+ theme(axis.text.x = element_text(angle = 90, hjust = 1)))

grid.arrange(p1,p2,p3)

  
}
```



